### ISSUE TITLE
doc location seems to be recursive/broken.. 

### ISSUE THREAD

**Issue by BarDweller** [OpenLiberty/ci.docker#10]
Readme : https://github.com/OpenLiberty/ci.docker/blob/master/release/kernel/README.md
says "Instructions for using the image can be found on Docker Hub"

Over on docker hub.. 
https://hub.docker.com/r/openliberty/open-liberty/
The text also says "Instructions for using the image can be found on Docker Hub", and the Docker Hub bit is a link, (but all the links in the text give 404 when followed)

**Comment by davidcurrie** [comment]
So the default when an automatic build is to populate the docs with the README from the repo it's building from which is where this text has come from. It can be easily edited now if someone can suggest some suitable replacement text.

**Comment by NottyCode** [comment]
@BarDweller I believe this has been fixed since we worked out how the docs worked.
