### ISSUE TITLE
server.xml's for docker images don't have host="*" set

### ISSUE THREAD

**Issue by BarDweller** [OpenLiberty/ci.docker#11]
When using the images from here, without host="*" set, I couldn't talk to my liberty via the docker port forward.. 

But adding a server.xml to set host="*" meant I overrode the one supplied as part of the tagged image, meaning I had to set the features up etc, losing me the convenience of just using the tagged image. 
(Tho I guess I could have configured host via config dropins.. it would be nicer to just be able to 'use' a docker image like this, by adding in my app to dropins folder, and not have to worry about changing the host setting.. )

**Comment by davidcurrie** [comment]
Agreed - I hadn't spotted this was already the case. PRs are welcome if you want the changes quickly! :)
