### ISSUE TITLE
Docker files for Java 11 for 19.0.0.10 and 19.0.0.11

### ISSUE THREAD

**Issue by dannemano** [OpenLiberty/ci.docker#120]
Hi,

We are using open-liberty:19.0.0.9-kernel-java11 as base image for our custom images.

Just wondering why open liberty hasn´t been packaged with Java 11 for 19.0.0.10 and 19.0.0.11?

What is the strategy going forward? Should we modify the kernel-image it self or can we wait for a upcoming open-liberty:19.0.0.11-kernel-java11?

**Comment by arthurdm** [comment]
hey @dannemano - we're working on having Java 11 Open Liberty images based on UBI with the latest fixpack.  Coming soon.

**Comment by dannemano** [comment]
Sounds great! Thanks!

**Comment by dannemano** [comment]
Closing this as good stuff is on its way.

**Comment by verymahler** [comment]
It looks like the PR was merged quite a while ago
https://github.com/docker-library/official-images/pull/6943
This item was opened only 3 days after the merge and now it's 17 days after the merge.
Any update? Any way people can help?
