### ISSUE TITLE
Availability of Docker images for the latest Open Liberty version

### ISSUE THREAD

**Issue by rieckpil** [OpenLiberty/ci.docker#125]
Do you currently plan to update the official Docker images at https://hub.docker.com/_/open-liberty with each release of Open Liberty? Right now `open-liberty:kernel-java11` is using Open Liberty 19.0.0.10 and two versions "behind".

**Comment by leochr** [comment]
@rieckpil Red Hat's Universal Base Images (UBI) for Open Liberty has the latest version with Java 11. It's our recommended set, so please consider using it: https://hub.docker.com/r/openliberty/open-liberty

Ubuntu-based images were recently restructured to simplify the tags and we only provide Java 8 based images at the moment.

**Comment by rieckpil** [comment]
thanks @leochr for the information. I wasn't aware of this image and always used this in the past: https://hub.docker.com/_/open-liberty
