### ISSUE TITLE
Confusing settings for OpenJ9 shared classs cache 

### ISSUE THREAD

**Issue by ashu-mehra** [OpenLiberty/ci.docker#126]
The [Dockerfile](https://github.com/OpenLiberty/ci.docker/blob/504fdf26e680b1f71de82ac4099044cb55e8e2d8/releases/latest/kernel/Dockerfile.ubuntu.adoptopenjdk8#L72) sets SCC location to `cacheDir=/output/.classCache/` but when I run the server and check the location in javacore, I see it as `cacheDir="/opt/ol/wlp/output/.classCache"`.
It appears the `IBM_JAVA_OPTIONS` is getting overwritten by `/opt/ol/wlp/bin/server`.

Also the `configure.sh` script ends up removing the cache at the [last step](https://github.com/OpenLiberty/ci.docker/blob/504fdf26e680b1f71de82ac4099044cb55e8e2d8/releases/latest/kernel/helpers/build/configure.sh#L81).
So if some one runs `configure.sh` script in their Dockerfile, they won't be able to get the startup benefit that SCC can provide during the runtime.

**Comment by jdmcclur** [comment]
I'm hoping this takes care of it: https://github.com/OpenLiberty/open-liberty/issues/9662

**Comment by jdmcclur** [comment]
This should be fixed now, only /output/.classCache/ is used with the docker images.

**Comment by ashu-mehra** [comment]
@jdmcclur thanks for the update!
