### ISSUE TITLE
Dockerhub links to docker file are incorrect

### ISSUE THREAD

**Issue by altenbueGHE** [OpenLiberty/ci.docker#13]
The links on the Open Liberty Dockerhub page https://hub.docker.com/r/openliberty/open-liberty/ are broken when linking to the "Dockerfile"  and the image on "Docker Hub".

The Dockerfile link should be: https://hub.docker.com/r/openliberty/open-liberty/~/dockerfile/
I *think* the Docker Hub link should be: https://hub.docker.com/u/openliberty/

**Comment by NottyCode** [comment]
@altenbueGHE I think this is fixed. There was a problem where the documentation on the docker hub page kept being reset to a default that was broken, but I believe that has since been fixed.
