### ISSUE TITLE
java11 hotspot images

### ISSUE THREAD

**Issue by kvenkatramreddy** [OpenLiberty/ci.docker#133]
Please, could you provide openLiberty images with OpenJDK11 Hotspot as well?

**Comment by vijaysun-omr** [comment]
OpenJDK with OpenJ9 has been optimized to work best with Open Liberty in terms of startup time, memory footprint in particular (and generally speaking, it is the better choice performance-wise). As such, OpenJDK with OpenJ9 is the recommended (strategic) JVM of choice to run with Open Liberty for these reasons.

**Comment by arthurdm** [comment]
Thanks for your request @kvenkatramreddy - as outlined by Vijay above, using the OpenJ9 images is the recommended path.      Is there a particular reason you wanted Hotspot?

**Comment by kvenkatramreddy** [comment]
Hi,

We are using Apache Ignite In-Memory Grid data platform as embedded in my web application and we are observing a lot of GC pauses and their help guide shows GC tuning for the only HotSpot. So we want to try with OpenJDK hotspot 

Thanks & Regards,
Venkat

**Comment by arthurdm** [comment]
Thanks for the info @kvenkatramreddy 

If you just want to try out that variant, you could use [this Dockerfile](https://github.com/OpenLiberty/ci.docker/blob/master/releases/latest/kernel/Dockerfile.ubi.adoptopenjdk11) and just change the `FROM` to `adoptopenjdk/openjdk11:ubi`.   If you `docker build` that updated Dockerfile you'll have the image you're looking for.

**Comment by kvenkatramreddy** [comment]
@arthurdm 
Thank you very much.
