### ISSUE TITLE
configure.sh script is confusing

### ISSUE THREAD

**Issue by MaiHameed** [OpenLiberty/ci.docker#141]
When using the OL Docker images in our applications for our guides, as well as during workshops, a common comment that I receive and have noticed is that the console output is not user friendly. The red text when running the script as well as the messages stating that the server has been stopped is  is initially confusing for myself and others. 

Just wanted to bring it to light :)

**Comment by arthurdm** [comment]
thanks for the feedback @MaiHameed!   We have heard this feedback as well, so looks like something we need to address. 

Ideally it would be good to have no output from configure.sh unless an `ARG` such as `verbose` is set to true.

**Comment by JusteenR** [comment]
Closed at #144
