### ISSUE TITLE
Update to 20.0.0.x + Java 11 + OpenJ9

### ISSUE THREAD

**Issue by verymahler** [OpenLiberty/ci.docker#148]
Is there still a new image coming for the **Open Liberty 20.0.0.x** + **Java 11**?
Version 19.0.012 + Java8 is the latest version I could find here https://hub.docker.com/_/open-liberty

**Comment by edavidj** [comment]
That link is for our Ubuntu based images, which only support 20.0.0.2 on Java 8 at the moment (see `open-liberty:kernel-java8-openj9`). For Open Liberty 20.0.0.2 + Java 11, and other options based on UBI, see [openliberty/open-liberty:kernel-java11-openj9](https://hub.docker.com/layers/openliberty/open-liberty/kernel-java11-openj9-ubi/images/sha256-781fa9dbe7cae68faaab38de80ae22b07069e0e3d3f4ba98e82ac88b125103a3?context=explore) or [openliberty/open-liberty:full-java11-openj9](https://hub.docker.com/layers/openliberty/open-liberty/full-java11-openj9-ubi/images/sha256-2682bda9da988cce595aabcc661441339c870e8eb937229653b7ccc18d301138?context=explore).

That said the Docker Hub README there does not make this clear, only briefly mentioning the other repo in the Overview section. This is something that could be improved, I'll look into opening a separate issue for that.

**Comment by verymahler** [comment]
Ok thanks.
