### ISSUE TITLE
Improve Docker Hub README's

### ISSUE THREAD

**Issue by edavidj** [OpenLiberty/ci.docker#149]
Currently the Docker Hub README's for [open-liberty](https://hub.docker.com/_/open-liberty) and [openliberty/open-liberty](https://hub.docker.com/r/openliberty/open-liberty) are not up to date in terms of how they relate to each other and what images are available.  

This results in a lot of confusion about how to get the latest versions of liberty, and a lot of people unaware that the majority of our images are in the `openliberty/open-liberty` repo. I propose something similar to [adoptopenjdk](https://hub.docker.com/r/adoptopenjdk/openjdk11)'s README, which immediately highlights the differences between the two, with links to the other.

**Comment by cwansart** [comment]
I agree here. https://openliberty.io/downloads/#getOL and also the example in the README here (section _Building an application image_) both use the container `open-liberty` instead of the `openliberty/open-liberty` container.
This is strange since the section above (_Docker Hub images_) states that `openliberty/open-liberty` containers are the preferred ones.

**Comment by cwansart** [comment]
This issue would be resolved with https://github.com/OpenLiberty/ci.docker/pull/159 wouldn't it?

**Comment by edavidj** [comment]
> This issue would be resolved with #159 wouldn't it?

I still need to update the documentation on the official [DockerHub](https://hub.docker.com/_/open-liberty) itself, so I'll keep this open until that's complete. That update will come from https://github.com/docker-library/docs for open-liberty and websphere-liberty. Hoping to get to that today/tomorrow.

**Comment by edavidj** [comment]
Documentation for Docker Hub official repos has been updated. I'll look into opening a separate issue for potentially updating https://openliberty.io/downloads/#getOL  to point to the preferred UBI images. Closing.
