### ISSUE TITLE
container cannot be started in read-only mode

### ISSUE THREAD

**Issue by PhilippParis** [OpenLiberty/ci.docker#158]
if the docker container uses a read-only filesystem startup fails with:
`cp: cannot create regular file '/config/configDropins/overrides/trustDefault.xml': Read-only file system`
even if the keystore is build into the image

a possible solution would be to copy the trustDefault.xml file during build instead at runtime.

tested with image 20.0.0.3-full-java11-openj9-ubi

**Comment by arthurdm** [comment]
@arturdzm - I guess the new cert manager support has limitations in terms of supporting read-only filesystems.   Probably something we should: (a) look to see if improvements can be made, and (b) document the limitations.

**Comment by arthurdm** [comment]
@arturdzm - can you please explore a flag (env var) to avoid going down the path of manipulating trustDefault.xml?    If someone already has the TLS / cert snippets configured during their image build there should be a way to turn off any need for Liberty to write it during container startup.

**Comment by arturdzm** [comment]
Should be fixed now with #177
