### ISSUE TITLE
Add ifix instructions / script

### ISSUE THREAD

**Issue by arthurdm** [OpenLiberty/ci.docker#169]
This workitem will add the equivalent to the ifix support available in the WebSphere Liberty container, illustrated here: https://github.com/WASdev/ci.docker/tree/master/ga/applying-ifixes

So the work involves:
* adding a new `applfying-ifixes` page in this repository
* adding similar configure.sh support as https://github.com/WASdev/ci.docker/blob/master/ga/latest/kernel/helpers/build/configure.sh#L106

**Comment by leochr** [comment]
Delivered.
