### ISSUE TITLE
Question: Startup time of open-liberty docker images quite long

### ISSUE THREAD

**Issue by BastianSperrhacke-Otto** [OpenLiberty/ci.docker#174]
Hi guys.
I'm just playin' around with the openliberty as an alternative server for our jakarta EE Applications.
In the community I heard quite good reputations and the startup times mentioned in your website looks promising.
Because of our cloud native style we autoscale our servers on AWS Fargate, which makes the startup time an important parameter.
When I just start an docker container locally (i7, 4 cores, 32 gb ram, windows) and on an ubuntu docker deamon machine (2 cpus, 8gb ram EC2 m5.large) I just experienced startup times around 12 seconds (full openliberty) and around 3 seconds (kernel image), without any application deployed.
see my output here:
`docker run open-liberty:20.0.0.3-full-java8-openj9

Launching defaultServer (Open Liberty 20.0.0.3/wlp-1.0.38.cl200320200305-1433) on Eclipse OpenJ9 VM, version 1.8.0_252-b09 (en_US)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/keystore.xml
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/open-default-port.xml
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/overrides/trustDefault.xml
[AUDIT   ] CWWKG0102I: Found conflicting settings for defaultSSLConfig instance of ssl configuration.
  Property trustDefaultCerts has conflicting values:
    Value true is set in file:/opt/ol/wlp/usr/servers/defaultServer/server.xml.
    Value ${SEC_TLS_TRUSTDEFAULTCERTS} is set in file:/opt/ol/wlp/usr/servers/defaultServer/configDropins/overrides/trustDefault.xml.
  Property trustDefaultCerts will be set to ${SEC_TLS_TRUSTDEFAULTCERTS}.

[WARNING ] CWWKS3103W: There are no users defined for the BasicRegistry configuration of ID com.ibm.ws.security.registry.basic.config[basic].
[AUDIT   ] CWWKZ0058I: Monitoring dropins for applications.
[AUDIT   ] CWWKS4104A: LTPA keys created in 1.930 seconds. LTPA key file: /opt/ol/wlp/output/defaultServer/resources/security/ltpa.keys
[AUDIT   ] CWPKI0803A: SSL certificate created in 4.219 seconds. SSL key file: /opt/ol/wlp/output/defaultServer/resources/security/key.p12
[AUDIT   ] CWWKF0012I: The server installed the following features: [appClientSupport-1.0, appSecurity-2.0, appSecurity-3.0, batch-1.0, beanValidation-2.0, cdi-2.0, concurrent-1.0, distributedMap-1.0, ejb-3.2, ejbHome-3.2, ejbLite-3.2, ejbPersistentTimer-3.2, ejbRemote-3.2, j2eeManagement-1.1, jacc-1.5, jaspic-1.1, javaMail-1.6, javaee-8.0, jaxb-2.2, jaxrs-2.1, jaxrsClient-2.1, jaxws-2.2, jca-1.7, jcaInboundSecurity-1.0, jdbc-4.2, jms-2.0, jndi-1.0, jpa-2.2, jpaContainer-2.2, jsf-2.3, jsonb-1.0, jsonp-1.1, managedBeans-1.0, mdb-3.2, servlet-4.0, ssl-1.0, wasJmsClient-2.0, wasJmsSecurity-1.0, wasJmsServer-1.0, webProfile-8.0, websocket-1.1].
[AUDIT   ] CWWKF0013I: The server removed the following features: [servlet-3.1].
[AUDIT   ] CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 11.364 seconds.
[AUDIT   ] CWWKI0001I: The CORBA name server is now available at corbaloc:iiop:localhost:2809/NameService.
`
Is there something missing to configure?

Thanks and best regards.

Bastian

**Comment by jdmcclur** [comment]
@arthurdm - For the full image, it looks we need to add another layer to the shared class cache like we do in the websphere-libery image (https://github.com/WASdev/ci.docker/blob/master/ga/latest/full/Dockerfile.ubuntu.ibmjava8#L28-L32)

Running docker pinned to 2 cpus in my Ubuntu bare metal Haswell environment, this brings the startup time from 10s down to 4.5s.
```
# Create a new SCC layer
RUN if [ "$OPENJ9_SCC" = "true" ]; then populate_scc.sh; fi \
    && rm -rf /output/messaging /output/resources/security /logs/* $WLP_OUTPUT_DIR/.classCache \
    && chown -R 1001:0 /opt/ol/wlp/output \
    && chmod -R g+rwx /opt/ol/wlp/output
```

For the kernel image, I don't have exactly the same env as you, but I am seeing 1.3s startup times with 2 cpus.

**Comment by ymanton** [comment]
This should be fixed by https://github.com/OpenLiberty/ci.docker/pull/175.

**Comment by jdmcclur** [comment]
I should also mention, the full image is more for convenience as it enables a lot of features you probably don't need. 

For best performance use the kernel image with only the features that you do need in the server.xml. When development is done, put this at the end of your Dockerfile, which helps with startup performance, but It takes a bit to run (less than a minute usually), so you may not want to use it during development/every time you build the container.
```
RUN configure.sh
```

**Comment by arthurdm** [comment]
looks like this issue has been resolved by the linked PRs.  If you still see an issue please feel free to open it.
