### ISSUE TITLE
Failed to run configure.sh

### ISSUE THREAD

**Issue by gkwan-ibm** [OpenLiberty/ci.docker#181]
If Dockerfile has `FROM open-liberty` and `RUN configure.sh`, when build it, got this error:
```
The command '/bin/sh -c configure.sh' returned a non-zero code: 1
```
When add `ARG VERBSOE=true` in Dockerfile, will have following
```
+ chmod -R g+rwx '/output/resources/*'
chmod: cannot access '/output/resources/*': No such file or directory
```

**Comment by jwalcorn** [comment]
This sounds related to the earlier issues I raised on the #was-docker channel.  That led to PR #179  and PR #180 being delivered, and the results being pushed to DockerHub.  Sounds like we need one more round to get it perfectly correct.

**Comment by jwalcorn** [comment]
<img width="345" alt="image" src="https://user-images.githubusercontent.com/28963246/81965739-808d9300-95e6-11ea-8c4a-3ed11adb0dab.png">

**Comment by arthurdm** [comment]
@gkwan-ibm - once this PR (https://github.com/docker-library/official-images/pull/8011) gets merged then the images will be rebuilt.

**Comment by arthurdm** [comment]
Fix is now available in the images.  Please re-pull and retry.

**Comment by gkwan-ibm** [comment]
Verified and the problem was resolved.
