### ISSUE TITLE
Provide JDK 14 images

### ISSUE THREAD

**Issue by ggam** [OpenLiberty/ci.docker#183]
Only JDK 8, 11 and 13 images are provided. JDK 14 is the latest and is already supported in Open Liberty 20.0.5.

**Comment by arthurdm** [comment]
yup, agreed.

We should replace the JDK 13 image tags with JDK 14, using `adoptopenjdk/openjdk14-openj9` as the base.   This should apply to the 20.0.0.5 and `latest` tags.  

For the other tags, simply remove the JDK 13 folder, as those are no longer supported.

**Comment by InfTkm** [comment]
JDK 14 support is added. Closing the issue now.
