### ISSUE TITLE
Make use of featureUtility for minimum sized kernel images

### ISSUE THREAD

**Issue by NottyCode** [OpenLiberty/ci.docker#193]
20.0.0.6 introduces featureUtility to Liberty which enables you to start from a kernel image and on the command line add features. These features will be downloaded and installed from a maven repository.

We need to produce kernel images that take advantage of this. Some considerations:

1. The kernel feature currently has all features so this change could be a breaking change since someone updating could end up with a broken docker file
2. We want to have optimally layered images, which means a pattern that allows installing features before adding the application.
3. We need to ensure that we prime a multi-layered shared class cache and workarea to ensure we have the best startup when deployed into production.
4. There should be no scenario where the server outputs on docker run that features were uninstalled (this has been seen in the past).

**Comment by yeekangc** [comment]
@scottkurz @gkwan-ibm @ericglau

**Comment by scottkurz** [comment]
Perhaps we should, along with this update **configure.sh** so that a Dockerfile depending on an existing tag like "kernel-java8-openj9-ubi" continues to work with this tag repurposed to provide a minimal kernel.   

That is, allow a simple build like:

```
  FROM openliberty/open-liberty:kernel-java8-openj9-ubi
 # Add my app and config
 COPY --chown=1001:0  Sample1.war /config/dropins/
 COPY --chown=1001:0  server.xml /config/
 # This script will add the requested XML snippets, grow image to be fit-for-purpose and apply interim fixes
 RUN configure.sh
```
to continue to work even though the layering will be sub-optimal (with apps now layered in before features) ?

**Comment by arthurdm** [comment]
I agree that would be the most reasonable approach @scottkurz - but I know there's a lot of users that still don't use `configure.sh`, so they would be broken.  

We may rationalize that it's OK to do that in the version-less tags, and propagate that change going forward into the future versioned tags.

**Comment by gkwan-ibm** [comment]
As I know, if users use zipkin for opentracing, server.xml have to specify the `<feature>usr:opentracingZipkin-0.31</feature>` and the user feature should be available at the usr directory.

Does/Will this feature support to install user feature? If not, what is the solution for this case?

cc @fmhwong, fyi

**Comment by NottyCode** [comment]
@gkwan-ibm support for user features is covered by [8986](https://github.com/OpenLiberty/open-liberty/issues/8986).

**Comment by leochr** [comment]
@NottyCode We are planning to introduce a new tag to avoid breaking existing users who use the `kernel` tag. We are thinking to name the new tag `kernel-min`. Another suggestion was `kernel-core` but we were worried if the term _core_ could confuse users in terms of Liberty licensing. Please let us know your thoughts including any other naming suggestions. Thank you.

**Comment by yeekangc** [comment]
So, IIUC, we will have `kernel` and then a `kernel-min`?  `kernel-min` will be new and specific to our Docker images, right?  There is no notion of a minimal kernel on the runtime side?

**Comment by leochr** [comment]
@yeekangc That's right. Only specific to Docker images. 

Naming is always hard. Hence, we request feedback from everyone on the new name `kernel-min` and/or suggestions for better alternatives.

**Comment by NottyCode** [comment]
kernel-min could also be confusing with ubi-min vs ubi. I agree that kernel-core is totally out of the question.

**Comment by ewoudwerkman** [comment]
`kernel-base`?

**Comment by leochr** [comment]
Thank you @ewoudwerkman for the suggestion. `base` is also used for Liberty licensing, similar to `core`, hence could cause confusion.

**Comment by arthurdm** [comment]
hey @leochr - looks like we have the following tags for the version-less `kernel`:

```
open-liberty:kernel
open-liberty:kernel-java8-openj9
openliberty/open-liberty:kernel-java8-openj9-ubi
openliberty/open-liberty:kernel-java8-ibmjava-ubi
openliberty/open-liberty:kernel-java11-openj9-ubi
openliberty/open-liberty:kernel-java14-openj9-ubi
```

Then we have the versioned variants for them which add a prefix such as `20.0.0.9-`, etc.  So I am thinking maybe we just switch to a model where we prefix the version-less tags with `latest`, for example:

```
open-liberty:latest-kernel
open-liberty:latest-kernel-java8-openj9
openliberty/open-liberty:latest-kernel-java8-openj9-ubi
openliberty/open-liberty:latest-kernel-java8-ibmjava-ubi
openliberty/open-liberty:latest-kernel-java11-openj9-ubi
openliberty/open-liberty:latest-kernel-java14-openj9-ubi
```

This way, since they are new tags, we can use the `real` kernel - without breaking any existing usages.

**Comment by ewoudwerkman** [comment]
Naming is indeed hard ;-)
`kernel-slim`? 'slim' on docker image tags usually refer to a version where stuff has left out, while trying to get a minimal image.

**Comment by yeekangc** [comment]
@leochr, can you please update and indicate what are we going (in terms of the name) with and doing with this issue?

**Comment by yeekangc** [comment]
Btw, is this a feature?  If so, can I have a pointer to the UFO?

**Comment by leochr** [comment]
@yeekangc Based on the feedback from folks, we picked `kernel-slim`. The 20.0.0.11 images with the new tag are in Docker Hub now.

This is the feature for OL runtime I believe, it has a link to UFO: https://github.com/OpenLiberty/open-liberty/issues/9227

**Comment by leochr** [comment]
Delivered. Closing.

**Comment by ericglau** [comment]
The following issue is needed for dev mode for containers to support the `kernel-slim` image: https://github.com/OpenLiberty/ci.maven/issues/811

**Comment by yeekangc** [comment]
Thanks, @leochr.  This is a separate issue in the backlog so I thought it would be a separate feature (covering what is needed to get to minimally-sized kernel container images).  Double checked and https://github.com/OpenLiberty/open-liberty/issues/9227 didn't seem to cover what is needed for container images.

In any case, we will work with 'kernel-slim' for what is needed and go from there.
