### ISSUE TITLE
Investigate vulnerabilities of UBI Images

### ISSUE THREAD

**Issue by edavidj** [OpenLiberty/ci.docker#194]
Investigate the removal of `httpd, nginx, perl, python, ghostscript, php, pip` components and how that might help vulnerabilities in UBI images.

**Comment by navidsh** [comment]
The packages listed in the description are all in the `ubi/ubi:8.2` image. We build our images on a daily basis and the images will pick up the updates in the UBI image. There's no need to remove any package.
