### ISSUE TITLE
Question: 20.0.0.9-kernel-java11 provided via DockerHub

### ISSUE THREAD

**Issue by DennisGruner** [OpenLiberty/ci.docker#202]
The last OpenLiberty Version on Dockerhub with java11 is 19.0.0.9-kernel-java11. I saw you have a Dockerfile with java11 and OL 20.0.09 ready. Why do you not publish this to DockerHub?

**Comment by arthurdm** [comment]
hi @DennisGruner - they are available in this repo (using UBI images): https://hub.docker.com/r/openliberty/open-liberty/

**Comment by DennisGruner** [comment]
Great Thx
