### ISSUE TITLE
Add java11 docker image

### ISSUE THREAD

**Issue by Emily-Jiang** [OpenLiberty/ci.docker#205]
We have java11 UBI docker image https://hub.docker.com/r/openliberty/open-liberty
However, https://hub.docker.com/_/open-liberty only have java8 images not having java11 docker images.
Please provide docker image for openj9 Java11. In this case, the two sites provide the equivalent docker images.

**Comment by leochr** [comment]
@Emily-Jiang Open Liberty images based on OpenJ9 Java 11 have been added for Ubuntu OS. For example, _full-java11-openj9_. Full list is [here](https://hub.docker.com/_/open-liberty?tab=tags&page=1&ordering=last_updated&name=java11-openj9).
