### ISSUE TITLE
UBI images are incorrectly tagged as ubi-min

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/ci.docker#208]
The following images are incorrectly tagged as `ubi-min`, but they are based on ubi

https://hub.docker.com/r/openliberty/open-liberty/tags?page=1&name=kernel-ubi-min

Especially `kernel-ubi-min` was updated on October 13, 2020. Others are old and haven't been updated lately (that's good).

We should stop updating this tag. When `ubi-min` based images are added by #207, we'll have a new tag called `kernel-slim-ubi-min`.

**Comment by arthurdm** [comment]
I believe @arturdzm found the spot in the code where this is happening.   Artur - can you please take a look into this one?

**Comment by leochr** [comment]
Addressed as part of 20.0.0.12 updates. Closing.
