### ISSUE TITLE
Provide JDK 15 images

### ISSUE THREAD

**Issue by verymahler** [OpenLiberty/ci.docker#220]
Only JDK 8, 11 and 14 images are provided. JDK 15 is the latest.

The JDK 14 image tags could be replaced with JDK 15, using `adoptopenjdk/openjdk15-openj9` as the base. 
This can apply from the versions of OpenLiberty that support JDK15 and latest tags.

Related to issue https://github.com/OpenLiberty/ci.docker/issues/183

**Comment by arthurdm** [comment]
thanks for opening this @verymahler!

@leochr - this is related to our chat about supported JDK tags.  Seems reasonable to make the switch from 14 to 15 now.

**Comment by leochr** [comment]
Open Liberty 20.0.0.12 will add Java 15 support. Created PR #222 to switch from Java 14 to 15 - only the `latest`

FYI @crpotter java version changes to upcoming release - for consideration in build

**Comment by verymahler** [comment]
This has been fixed with `openliberty/open-liberty:kernel-slim-java15-openj9-ubi`
