### ISSUE TITLE
beta version number is incorrect

### ISSUE THREAD

**Issue by tevans78** [OpenLiberty/ci.docker#229]
https://github.com/OpenLiberty/ci.docker/blob/51ff2606fcecbcb70c35fd69f3adcb214eb34c7b/releases/latest/beta/Dockerfile.ubuntu.adoptopenjdk8#L2

and

https://github.com/OpenLiberty/ci.docker/blob/51ff2606fcecbcb70c35fd69f3adcb214eb34c7b/releases/latest/beta/Dockerfile.ubuntu.adoptopenjdk11#L2

version should be `21.0.0.1-beta`

**Comment by idlewis** [comment]
Should be fixed by #230

**Comment by leochr** [comment]
Fixed. Closing.
