### ISSUE TITLE
Review chmod/chown operations to identify opportunities to reduce image size

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/ci.docker#233]
Dockerfiles and build/runtime scripts (i.e. configure.sh, features.sh, etc) and perform various chmod and chown operations. These operations increase the size of the image (when performed on a separate instruction than the one that created/copied/extracted those files). Review the instances of these operations to evaluate whether it's necessary and/or if the instruction can be optimized to reduce image size.

**Comment by leochr** [comment]
fyi @idlewis @yongja79

**Comment by jdmcclur** [comment]
Can this be closed?

**Comment by leochr** [comment]
Yes, already address. Thanks
