### ISSUE TITLE
Shared class cache embedded in the container is not used

### ISSUE THREAD

**Issue by mpirvu** [OpenLiberty/ci.docker#234]
I experimented with latest versions of `openliberty/open-liberty:20.0.0.12-kernel-slim-java8-openj9-ubi` and `openliberty/open-liberty:20.0.0.12-full-java8-openj9-ubi` and saw an increased startup time.
Upon further inspection it turns out that Liberty is trying to use a shared class cache (SCC) from `/opt/ol/wlp/output/.classCache` directory which does not exist (it will be created and populated at runtime, but this means increased start-up time). In the `configure.sh` script Liberty correctly determines that the docker layer it is based on, `adoptopenjdk/openjdk8-openj9:ubi`, has an embedded SCC at `/opt/java/.scc` and it builds another SCC layer on top it. However, at runtime, it decides to stick with the old `/opt/ol/wlp/output/.classCache` location.
I think this is an artifact of a recent change in the `adoptopenjdk/openjdk8-openj9:ubi` image where `OPEN9_JAVA_OPTIONS` is no longer defined. This change allows an user to provide their own JDK options through the documented `OPENJ9_JAVA_OPTIONS` environment variable, but it seems to have broken Liberty container behavior.

**Comment by mpirvu** [comment]
javacore shows the following arguments:
```
2CIUSERARG               -Xshareclasses:name=openj9_system_scc,cacheDir=/opt/java/.scc,readonly,nonFatal
2CIUSERARG               -Xshareclasses:name=liberty-%u,nonfatal,cacheDir=/opt/ol/wlp/output/.classCache,cacheDirPerm=1000
2CIUSERARG               -XX:ShareClassesEnableBCI
2CIUSERARG               -Xscmx80m
2CIUSERARG               -Xshareclasses:name=liberty-%u,nonfatal,cacheDir=/opt/ol/wlp/output/.classCache,cacheDirPerm=1000
2CIUSERARG               -XX:ShareClassesEnableBCI
2CIUSERARG               -Xscmx80m
```
Note the multiple definition of the -Xshareclasses command line option

@ymanton @jdmcclur

**Comment by jdmcclur** [comment]
If there is no shareclasses defined anywhere our server script will use the old location, so we'll need to define it if it's not defined. I'll take a look later today.

**Comment by jdmcclur** [comment]
The Ubuntu images look ok
```
OPENJ9_JAVA_OPTIONS=-Xshareclasses:name=openj9_system_scc,cacheDir=/opt/java/.scc,readonly,nonFatal
```

The UBI images do not, The shareclasses has been moved to JAVA_TOOL_OPTIONS.
```
JAVA_TOOL_OPTIONS=-XX:+IgnoreUnrecognizedVMOptions -XX:+IdleTuningGcOnIdle -Xshareclasses:name=openj9_system_scc,cacheDir=/opt/java/.scc,readonly,nonFatal
```

So, do we fix the server script to look at JAVA_TOOL_OPTIONS also, or specifically set OPENJ9_JAVA_OPTIONS.

Ugh, wonder if this affects all the utility scripts also.

**Comment by veenarm** [comment]
Is this only an issue with 20.0.0.12?
I'm running: openliberty/open-liberty:20.0.0.10-full-java8-openj9-ubi

coredump
2CIUSERARG               -Xshareclasses:name=liberty,nonfatal,cacheDir=/output/.classCache/
2CIUSERARG               -Xshareclasses:name=liberty,nonfatal,cacheDir=/output/.classCache/
2CIENVVAR      OPENJ9_JAVA_OPTIONS=-Xshareclasses:name=liberty,nonfatal,cacheDir=/output/.classCache/
2CIENVVAR      IBM_JAVA_OPTIONS=-Xshareclasses:name=liberty,nonfatal,cacheDir=/output/.classCache/

2CIENVVAR      JAVA_TOOL_OPTIONS=-XX:+IgnoreUnrecognizedVMOptions -XX:+UseContainerSupport -XX:+IdleTuningCompactOnIdle -XX:+IdleTuningGcOnIdle

**Comment by mpirvu** [comment]
"openliberty/open-liberty:20.0.0.10-full-java8-openj9-ubi" does not have the issue.

**Comment by jdmcclur** [comment]
Adding this near the end of Dockerfile for the ubi builds seems to work fine, but I know we do some work to make sure the scc exists/permissions are ok in populate_scc.sh, so not sure at the guarantee of this being correct. 
```
ENV OPENJ9_JAVA_OPTIONS=-Xshareclasses:name=openj9_system_scc,cacheDir=/opt/java/.scc,readonly,nonFatal
```

We could also update the server script to not specifiy a SCC if it finds one on JAVA_TOOL_OPTIONS, but that could take awhile to get in a liberty build.

Thoughts? @ymanton @mpirvu

**Comment by ymanton** [comment]
Setting `ENV OPENJ9_JAVA_OPTIONS=-Xshareclasses:name=openj9_system_scc,cacheDir=/opt/java/.scc,readonly,nonFatal` in the Liberty containers is fine and should work.

What exactly do the OpenJ9 image authors want to happen with downstream images? Do they want to specify a default set of options or do they want downstream images to get a blank slate? Why do Ubuntu images still set `OPENJ9_JAVA_OPTIONS`?

**Comment by mpirvu** [comment]
> What exactly do the OpenJ9 image authors want to happen with downstream images? 

The goal with moving the SCC options from OPENJ9_JAVA_OPTIONS to JAVA_TOOL_OPTIONS was to allow users to specify other JVM options (through OPENJ9_JAVA_OPTIONS) without rendering the embedded SCC useless. Without this change a user that wants to set, say `OPENJ9_JAVA_OPTIONS=-XX:UseJITServer` would have to know about the internals of the OpenJ9 image and set `OPENJ9_JAVA_OPTIONS="-Xshareclasses:name=openj9_system_scc,cacheDir=/opt/java/.scc,readonly,nonFatal -XX:UseJITServer"`

> Why do Ubuntu images still set OPENJ9_JAVA_OPTIONS?

Are those official builds  or un-official? The official builds were not touched.

**Comment by jdmcclur** [comment]
@ymanton - it looks like Ubuntu images actually do not set OPENJ9_JAVA_OPTIONS anymore, but that change hasn't made it to an image yet? 
https://github.com/AdoptOpenJDK/openjdk-docker/commit/50d5f52aab8eb8ed0f309d579b33c68bd4f87648#diff-048a3c3c047719623540fac4a6dc3eb696af4a800ed1ab1d8cdc4ffb870dbbe2

**Comment by ymanton** [comment]
I've opened #238 to deal with this by setting OPENJ9_JAVA_OPTIONS to the same string as JAVA_TOOL_OPTIONS. Ideally it would be better to set it by reading JAVA_TOOL_OPTIONS, but since not all of the images have the change yet I had to use the hardcoded string instead.
