### ISSUE TITLE
Server uses stale cached server.xml rather than the one copied into the image

### ISSUE THREAD

**Issue by jwalcorn** [OpenLiberty/ci.docker#244]
Sometimes when I docker build my Open Liberty-based microservice, it ends up not working, because it ignores the server.xml I copy into the image, and instead somehow still uses the built-in server.xml from the base OL image.  When this happens, when I run my image (whether in OpenShift, or just via "docker run"), it doesn't load any of my listed features, but instead just loads `jsp-2.3`.  My Dockerfile is here: https://github.com/IBMStockTrader/broker/blob/master/Dockerfile, and my server.xml is here: https://github.com/IBMStockTrader/broker/blob/master/src/main/liberty/config/server.xml.  Here's the results of running the image I built (which I pushed to the IBM Container Registry at us.icr.io/ibm-stock-trade/broker:error):
```
jalcorn@Johns-MBP-8 broker % docker run -it us.icr.io/ibm-stock-trader/broker:error bash
bash-4.4$ cd /opt/ol/wlp/bin/
bash-4.4$ server run defaultServer

Launching defaultServer (Open Liberty 21.0.0.1/wlp-1.0.48.cl210120210113-1459) on Eclipse OpenJ9 VM, version 11.0.10+9 (en_US)
[AUDIT   ] CWWKE0001I: The server defaultServer has been launched.
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/keystore.xml
[AUDIT   ] CWWKG0093A: Processing configuration drop-ins resource: /opt/ol/wlp/usr/servers/defaultServer/configDropins/defaults/open-default-port.xml
[AUDIT   ] CWWKG0028A: Processing included configuration resource: /opt/ol/wlp/usr/servers/defaultServer/includes/basic.xml
[ERROR   ] CWWKF0001E: A feature definition could not be found for jsp-2.3
[AUDIT   ] CWWKF0011I: The defaultServer server is ready to run a smarter planet. The defaultServer server started in 3.429 seconds.
^C[AUDIT   ] CWWKE0085I: The server defaultServer is stopping because the JVM is exiting.
[AUDIT   ] CWWKE1100I: Waiting for up to 30 seconds for the server to quiesce.
[AUDIT   ] CWWKE0036I: The server defaultServer stopped after 7 minutes, 21.027 seconds.
bash-4.4$ exit
```

**Comment by jwalcorn** [comment]
Discussed this with some of the Liberty Docker team at https://ibm-cloud.slack.com/archives/C32494NQ6/p1613010638074200.  One thing pointed out was that I do an include of another XML file from my server.xml, and use an environment variable in the path of what to include, so it's possible I'm hitting something related to https://github.com/OpenLiberty/open-liberty/issues/15698.

**Comment by jwalcorn** [comment]
My latest theory is that it's related to the timestamp on the server.xml.  If I `docker run -it us.icr.io/ibm-stock-trader/broker:error bash` then do a `./server.sh run defaultServer`, the problem happens.  But the timestamp on my server.xml (as shown via `ls -l /config/server.xml`) is December 9th.  Whereas the built-in server.xml for 21.0.0.1 is from January.  Though it shouldn't be this way, it's possible Liberty thinks it doesn't need to read the server.xml I copied into the image because it is older than the cached built-in one.  If I just `touch /config/server.xml` and then `./server.sh run defaultServer` from within that container, the server starts just fine, using my custom server.xml.  I think I don't usually see this because usually I do a fresh "git clone https://github.com/IBMStockTrader/broker` and then run a build, thus getting fresh timestamps on the cloned files, whereas this time I used a directory I had lying around on my hard drive from earlier (since I knew nothing new had been done in that microservice lately - I was just rebuilding to get a fresher Liberty).  Anyway, haven't proven that theory, but the fact that it fails, but works if I just "touch" the file (which only tweaks the timestamp) suggests that could be the reason.  Note that I do run `features.sh` and `configure.sh` in my Dockerfile after copying in the custom server.xml, and you'd think that would have cleared/refreshed any caches, but perhaps not.  I suppose a workaround would be to add a `RUN touch /config/server.xml` to my Dockerfile, but that really shouldn't be necessary (if this theory is true).

**Comment by jwalcorn** [comment]
![image](https://user-images.githubusercontent.com/28963246/107728092-baddab00-6cb2-11eb-9488-bc9204aed7e2.png)

**Comment by brenthdaniel** [comment]
I think the timestamp is probably the culprit. The server makes the determination on whether to use the cached config by looking at the latest timestamp on a configuration file and checking it against the cached config timestamp. This would work fine with older server.xml files if it were only server.xml involved (it's a "not equal" check, not a "later than" check), but would not work if any of the files in configDropins or `includes/basic.xml` had the latest timestamp and exactly matched the config timestamp.

**Comment by jwalcorn** [comment]
OK, given that, should something change in Liberty to address this, or should I update my sample to demonstrate the use of `RUN touch /config/server.xml` in the Dockerfile to work around this?

**Comment by jwalcorn** [comment]
I suppose one thing Liberty could do is to itself, when constructing the Docker image, `touch` the built-in server.xml to have a date of like 2000-01-01 or something.

**Comment by jwalcorn** [comment]
I pushed the broken image to DockerHub, so just `docker run ibmstocktrader/broker:error` to see it happen.  I then pushed a working one (rebuilt after doing a `touch` of the server.xml) there too with the `latest` tag, for comparison.

**Comment by scottkurz** [comment]
The fact that the  **/config/configDropins/defaults/open-default-port.xml** timestamp seems to always match the config cache timestamp (which looks like it must be this file:  **/output/workarea/org.eclipse.osgi/9/data/configStamp** means that I think means you can recreate this with just a bunch of old configs.

I can recreate it consistently by doing:  
```bash
touch -t 202012220101 find $(src/main/liberty/config/ -type f)
```
and doing the docker build.

But if I do the same thing from a similar build starting from "full" rather than "kernel-slim" in the second stage, I don't see the same problem, my server goes on to update its config to use the correctly features configured.  

In fact, even if I try to force some kind of problem with the old config file on top of the "full" base image, and (unscientifically) do:
```bash
 rm /opt/ol/wlp/lib/*jsp*
rm /opt/ol/wlp/lib/features/*jsp*
```
I see the server go on to update its config with the correct features.

### GOTCHAS

Might be worth noting some gotchas.   

Most fundamentally, Docker layer caching is assuming that mtime differences DO NOT matter for caching, but Open Liberty DOES behave differently with respect to config mtime.   For a two-stage maven build like this it can get a bit slow to build with `--no-cache`, so just be aware.

Besides that, it's probably worth adding to the `.dockerignore` since this project copies the whole project content into the build container.. rather than just the pom.xml and src.   I'm not that familiar with the project so just mentioning as a bit of a warning.




1.  
2. The .dockerignore

**Comment by jwalcorn** [comment]
Just checking back in here.  Should I add `RUN touch /config/server.xml` to my Dockerfile, or is Liberty planning to do something (perhaps in `features.sh` or `configure.sh`?) to address this?  Having a server that won't start unless its built-in config is older than the config you are copying in means anyone just moving up to a newer base image (like to get a security vulnerability fix) will be likely to hit this.  Thanks.

**Comment by scottkurz** [comment]
@leochr  do you have an opinion on this?   

From @brenthdaniel's comments about the config timestamp I wonder if one option would be to delete the config timestamp built into workarea in these lines:   https://github.com/OpenLiberty/ci.docker/blob/e5c98ce3c4e730e42aac7fc23efbf30bb6a56517/releases/latest/kernel-slim/Dockerfile.ubi.adoptopenjdk11#L83-L85

(or maybe even delete the whole **workarea**)???


I don't know enough about the details of SCC to know if that interferes with the whole purpose of building the cache in the first place though.

**Comment by jdmcclur** [comment]
I don't fully understand what is going on here, but I think you would want to remove the timestamp/workarea before running populate_scc.sh. Does that work? If not, liberty is going to have to build the workarea on the next start, so it will be slower every start in a container. populate_scc.sh populates the SCC by starting/stopping the server, which also caches the workarea.

Two things majorly impact startup
1. Cached Workarea 
2. SCC (SharedClassCache) which is a cache of java classes. Some of those may come from the workarea (I am not sure), but mostly come from other locations (the jdk, ol/wlp/lib, etc). Adding @ymanton who can provide more detail.

**Comment by scottkurz** [comment]
\

> 
> 
> I don't fully understand what is going on here, but I think you would want to remove the timestamp/workarea before running populate_scc.sh. Does that work? If not, liberty is going to have to build the workarea on the next start, so it will be slower every start in a container. populate_scc.sh populates the SCC by starting/stopping the server, which also caches the workarea.
> 
> Two things majorly impact startup
> 
>     1. Cached Workarea
> 
>     2. SCC (SharedClassCache) which is a cache of java classes. Some of those may come from the workarea (I am not sure), but mostly come from other locations (the jdk, ol/wlp/lib, etc). Adding @ymanton who can provide more detail.

I'm not familiar with all this.. but the thing I didn't realize until now is we run a populate_scc.sh when building the OL base image .. not just when building the app image.   It's the cleanup after the former that I tried fixing in #246, which seems to get past the immediate problem.    I'm not really knowledgeable enough to be sure I didn't break something else though.

**Comment by ymanton** [comment]
> SCC (SharedClassCache) which is a cache of java classes. Some of those may come from the workarea (I am not sure), but mostly come from other locations (the jdk, ol/wlp/lib, etc). Adding @ymanton who can provide more detail.

As far as I know, the SCC will cache classes from wherever the application decides to load them, as long as they're loaded by the bootstrap classloader, application classloader, `java.net.URLClassLoader` or a subclass of it, or a custom classloader that uses the Java Helper API that ships with OpenJ9 and IBM JDK.

If JARs and classes are loaded from the workarea they will be cached in the SCC. Deleting the workarea will probably invalidate the cached versions in the SCC. I'm not sure what would happen if the workarea contents were later recreated and we started loading (essentially the same) classes from there on subsequent runs. I'd guess that the results would be conservatively correct (i.e. the right classes would be loaded at the end of the day), but we might be loading the classes and recompiling code from scratch and ignoring cached stuff because of timestamps or some other consistency check.

**Comment by jdmcclur** [comment]
Scott, ah yes, that should work. Starting the base image will be slower, but that is pointless anyway. I can measure to see if there is a big difference in the end result.

**Comment by leochr** [comment]
@scottkurz do you know whether WL's kernel images would have the same issue?

**Comment by jwalcorn** [comment]
Any news on this?  Like is this targeted for 21.0.0.3?  For now I'm doing the workaround of adding `RUN touch /config/server.xml` to my Dockerfile, but I'd rather not show such hacks in my public samples if it can be avoided.

**Comment by jwalcorn** [comment]
Oh, I see now this got fixed under another issue.  Fine.  Looking forward to getting a build with the fix.  Thanks!
