### ISSUE TITLE
kernel doesn't appear to have been updated to 18.0.0.1

### ISSUE THREAD

**Issue by yeekangc** [OpenLiberty/ci.docker#25]
The Dockerfile for kernel still says 17.0.0.4 at the moment:

https://github.com/OpenLiberty/ci.docker/blob/master/release/kernel/Dockerfile

Perhaps it is no longer meant to be used?  Not sure so opening this issue.

**Comment by arthurdm** [comment]
We're waiting for Docker Inc to pull this PR https://github.com/docker-library/official-images/pull/4209

**Comment by NottyCode** [comment]
The PR has been accepted now.
