### ISSUE TITLE
OpenShift ConfigMap - settings.xml file replacement breaks completely

### ISSUE THREAD

**Issue by veenarm** [OpenLiberty/ci.docker#250]
Container: X - Crash loop back off 
/opt/ol/helpers/runtime/docker-server.sh: line 55: /config/configDropins/defaults/keystore.xml: No such file or director

Whenever i try to do a file mapping of server.xml -> /config/server.xml the container juist crashes and wont get past this line and advises no file for keystore (which I know is incorrect).

When I remove the configmap overwrite it works fine, using OpenShift 3.11 with OpenLiberty 21.0.0.2 ubi JDK11

I am assuming it's a permission based issue? OR a timing based issue?

**Comment by arthurdm** [comment]
hey @veenarm - I wonder if your mapping is completely overriding the container's `/config` directory.    Have you tried doing an `oc exec` on the container to verify its contents?

**Comment by veenarm** [comment]
I'm sorry, it was getting very late and tiredness set in...
It was in fact over mounting the entire /config directory, I've resolved it by doing a few explicit mappings instead.
