### ISSUE TITLE
New docker tags for springBoot features from open-liberty

### ISSUE THREAD

**Issue by tjwatson** [OpenLiberty/ci.docker#26]
Once the Spring Boot features are included in an open-liberty release (Epic OpenLiberty/open-liberty#3169) we need to create new tags in docker that include the new features for Spring Boot.

**Comment by mrglavas** [comment]
@dazavala @tjwatson: I am working on the Open Liberty tags for Spring Boot on a branch here: https://github.com/mrglavas/ci.docker-1/tree/springboot-1-2.

**Comment by dazavala** [comment]
Summary of work completed for this issue:
* Add springBoot content to OpenLiberty image readmes: https://github.com/OpenLiberty/ci.docker/pull/32
* Update the openliberty images so they just track the open-liberty official ones: https://github.com/OpenLiberty/ci.docker/pull/30 
* Add tags for Spring Boot support: https://github.com/OpenLiberty/ci.docker/pull/29

**Comment by dazavala** [comment]
Hello, Michael.  The official open-liberty springBoot tags and readme additions are published at docker hub.  Closing the issue.
