### ISSUE TITLE
Reduce overall container size of our ubi images by basing them on ubi-jre.

### ISSUE THREAD

**Issue by jdmcclur** [OpenLiberty/ci.docker#265]
I mentioned this on an an issue for ubi-min, but think this deserves its own issue.

We should look into basing our images on ubi-jre instead of ubi.
Example: adoptopenjdk/openjdk8-openj9:ubi-jre vs adoptopenjdk/openjdk8-openj9:ubi

I think ubi-jre only packages the jre instead of the whole jdk.

For our ubuntu images we use jre images, so I would think we would want to do the same for ubi?
The differences in size is fairly high. Is there a reason customers need the whole jdk for ubi (and not for ubuntu)?

adoptopenjdk/openjdk11-openj9       ubi          590MB
adoptopenjdk/openjdk11-openj9       ubi-jre      376MB

adoptopenjdk/openjdk8-openj9        ubi          479MB
adoptopenjdk/openjdk8-openj9        ubi-jre      378MB

**Comment by jdmcclur** [comment]
Best case is using ubi-minimal-jre, but then yum (and maybe other things) do not work. I did switch to microdnf and things seemed to build fine.

adoptopenjdk/openjdk8-openj9  ubi-minimal-jre 271MB

**Comment by vijaysun-omr** [comment]
@leochr fyi for your thoughts when you have time

**Comment by leochr** [comment]
That is a significant difference in size. We'll definitely use the jre images when adding ubi-min support. As for existing ubi images, not sure if customers actually rely on the jdk (or why jdk images were chosen, perhaps jre images were not available at that time). Now that UBI images are available in Docker Hub, we'll be looking to move the ubi images into the official repo (where Ubuntu images are) and as part of this move, we could switch to jre or drop ubi images altogether and just have ubi-min.

**Comment by l3ender** [comment]
This would be great! We currently use Ubuntu rather than UBI due to the significant reduction in size.

**Comment by vijaysun-omr** [comment]
@leochr is the change to use jre planned, and if so, what is the outlook ?

**Comment by leochr** [comment]
@vijaysun-omr As customers could rely on the jdk in existing Liberty images, we are planning to create new UBI-based images (ubi-min or ubi-micro) with jre. Some prototype work is expected to start in 4Q. Given other priorities with operators, this would be a late 1Q deliverable.

**Comment by jdmcclur** [comment]
@verymahler - any idea why icr.io/appcafe/ibm-semeru-runtimes:open-8-jre-ubi-minimal  (446MB) is so big compared to the adoptopenjdk/openjdk8-openj9:ubi-minimal-jre (271MB) I found before?

**Comment by leochr** [comment]
JRE images will be used for ubi-min based images (tracked by https://github.com/OpenLiberty/ci.docker/issues/207). Closing.
