### ISSUE TITLE
Images for 21.0.0.9 are not available

### ISSUE THREAD

**Issue by pugmas** [OpenLiberty/ci.docker#275]
Possible cause:
`/bin/sh: 1: populate_scc.sh: Permission denied`

at:
https://app.travis-ci.com/github/OpenLiberty/ci.docker/jobs/535524267
and:
https://app.travis-ci.com/github/OpenLiberty/ci.docker/jobs/535524268

**EDIT:**
This has already been fixed. I am sorry.
https://app.travis-ci.com/github/OpenLiberty/ci.docker/builds/236919543

But there are still no images on docker hub.

**Comment by schowave** [comment]
When will the 21.0.0.9 docker image be published to docker hub?

**Comment by pugmas** [comment]
Available now. Thanks!
