### ISSUE TITLE
Java 17 (LTS) Support for OpenLiberty 21.0.0.10

### ISSUE THREAD

**Issue by schowave** [OpenLiberty/ci.docker#277]
As of now Java 17 is released and there is official OpenLiberty Support for OpenLiberty 21.0.0.10 (https://openliberty.io/blog/2021/10/01/java17-210010.html), it would be great to use a dockerized OpenLiberty 21.0.0.10 with Java 17!

**Comment by verymahler** [comment]
This might be used as a reference https://github.com/OpenLiberty/ci.docker/pull/222 for the necessary changes.

**Comment by five-iron** [comment]
Java 17 based images of IBM Semuru are [now available](https://hub.docker.com/_/ibm-semeru-runtimes?tab=description), but only for Ubuntu and CentOS. There are no UBI based java 17 images in the official or [unofficial repos](https://hub.docker.com/u/ibmsemeruruntime). What will be done here in response, just build new Ubuntu images only?

**Comment by leochr** [comment]
Java team is working on the UBI images for Java 17. Once that is available, we'll add Liberty images based on Java 17 for both UBI and Ubuntu. We expect them to be available by the end of January 2022.

**Comment by verymahler** [comment]
@leochr The Red Hat UBI images for Java 17 (IBM Semeru Runtime) seem to be available
https://catalog.redhat.com/software/containers/search?q=semeru%2017&p=1

**Comment by reindan** [comment]
The UBI images are available directly from IBM Cloud Container Registry:

icr.io/appcafe/ibm-semeru-runtimes:open-17-jdk-ubi-amd64
icr.io/appcafe/ibm-semeru-runtimes:open-17-jdk-ubi-ppc64le
icr.io/appcafe/ibm-semeru-runtimes:open-17-jdk-ubi-s390x
icr.io/appcafe/ibm-semeru-runtimes:open-17-jdk-ubi-minimal-amd64
icr.io/appcafe/ibm-semeru-runtimes:open-17-jdk-ubi-minimal-ppc64le
icr.io/appcafe/ibm-semeru-runtimes:open-17-jdk-ubi-minimal-s390x

IBM recommends using this registry anyway, rather than Docker Hub.

**Comment by verymahler** [comment]
The JRE images are also available

```
REPOSITORY                             TAG                                 IMAGE ID       CREATED         SIZE
icr.io/appcafe/ibm-semeru-runtimes     open-17-jdk-ubi-minimal-s390x       af5a954f1130   8 days ago      711MB
icr.io/appcafe/ibm-semeru-runtimes     open-17-jre-ubi-minimal-s390x       d6f063afdeee   8 days ago      492MB
icr.io/appcafe/ibm-semeru-runtimes     open-17-jre-ubi-s390x               548063b36792   8 days ago      427MB
icr.io/appcafe/ibm-semeru-runtimes     open-17-jdk-ubi-s390x               d26ad6d5e621   8 days ago      846MB
icr.io/appcafe/ibm-semeru-runtimes     open-17-jdk-ubi-minimal-amd64       cc362dad76c3   11 days ago     668MB
icr.io/appcafe/ibm-semeru-runtimes     open-17-jre-ubi-minimal-amd64       7663a9eaa4a5   11 days ago     446MB
icr.io/appcafe/ibm-semeru-runtimes     open-17-jre-ubi-amd64               1d13aac2d7f3   11 days ago     434MB
icr.io/appcafe/ibm-semeru-runtimes     open-17-jdk-ubi-amd64               4e16acd902b7   11 days ago     811MB
icr.io/appcafe/ibm-semeru-runtimes     open-17-jdk-ubi-minimal-ppc64le     641aa62ce8f1   11 days ago     819MB
icr.io/appcafe/ibm-semeru-runtimes     open-17-jre-ubi-minimal-ppc64le     80fc8bf53015   11 days ago     595MB
icr.io/appcafe/ibm-semeru-runtimes     open-17-jre-ubi-ppc64le             49fb334fab20   11 days ago     528MB
icr.io/appcafe/ibm-semeru-runtimes     open-17-jdk-ubi-ppc64le             e5a1be43a695   11 days ago     983MB
```

**Comment by verymahler** [comment]
The official [ibm-semeru-runtimes](https://hub.docker.com/_/ibm-semeru-runtimes) on Docker Hub seem more suitable

```
ibm-semeru-runtimes    open-17-jre-focal    aef60ef11916   2 weeks ago     260MB
ibm-semeru-runtimes    open-17-jdk-focal    f16a3863db58   2 weeks ago     482MB
ibm-semeru-runtimes    open-17-jre-centos7  e394f61418bb   6 weeks ago     386MB
ibm-semeru-runtimes    open-17-jdk-centos7  7efe1b16b1b0   6 weeks ago     608MB
  
ibm-semeru-runtimes    open-11-jre-focal    d9a0cc90641f   2 weeks ago     259MB
ibm-semeru-runtimes    open-11-jdk-focal    fd5d0b30b831   2 weeks ago     472MB
ibm-semeru-runtimes    open-11-jre-centos7  ddf4c4bec11d   2 months ago    384MB
ibm-semeru-runtimes    open-11-jdk-centos7  4a8250fd837a   2 months ago    597MB
  
ibm-semeru-runtimes    open-8-jre-focal     46296c38dc0d   2 weeks ago     259MB
ibm-semeru-runtimes    open-8-jdk-focal     af3a3f8dd354   2 weeks ago     360MB
ibm-semeru-runtimes    open-8-jre-centos7   df0f0bbd5fc7   2 months ago    385MB
ibm-semeru-runtimes    open-8-jdk-centos7   8eb1618aabb7   2 months ago    486MB
```

**Comment by leochr** [comment]
The manifests for multi-arch images in `icr.io/appcafe/ibm-semeru-runtimes` are missing. We've raised an issue [here](https://github.com/ibmruntimes/Semeru-Runtimes/issues/16) since we (Liberty images) are blocked by that.

We'll use the Java 17 image in the official repo [ibm-semeru-runtimes](https://hub.docker.com/_/ibm-semeru-runtimes) to build the Ubuntu-based Liberty image with Java 17. But official repos in Docker Hub can not have UBI images (that's a general Docker Hub limitation for UBI images). Hence, we need the above manifest issue to be resolved in order to build UBI-based Liberty images with Java 17.

**Comment by verymahler** [comment]
For some reason the `ibm-semeru-runtimes:open-17-jre-focal` image (260MB) is smaller than the `icr.io/appcafe/ibm-semeru-runtimes:open-17-jre-ubi-minimal-amd64` image (446MB) - the regular UBI image (434MB) is even smaller.

**Comment by verymahler** [comment]
A pull request for the Ubuntu-based Liberty images with Java 17 is available here https://github.com/OpenLiberty/ci.docker/pull/291

**Comment by verymahler** [comment]
With these latest merges, once the changes are available on Docker Hub, I suppose the issue can be closed.

**Comment by schowave** [comment]
Available now on docker hub: https://hub.docker.com/_/open-liberty. Thank you for the support!

**Comment by reindan** [comment]
The images available on docker hub are only those with Ubuntu. Java 17 UBI images are not available...

**Comment by leochr** [comment]
Java 17 images are now available for both UBI and Ubuntu. Closing.
