### ISSUE TITLE
Missing features in the docker image randomly after every other build

### ISSUE THREAD

**Issue by bogdanmuresan** [OpenLiberty/ci.docker#286]
Hello,

Every other build or 2 builds, we end up with a broken image, that has missing features.
This seems to have started after updating to 21.0.0.10-kernel-slim-java11-openj9

The Dockerfile is something like this (simplified version):
```
FROM open-liberty:21.0.0.10-kernel-slim-java11-openj9
.
.
.
ADD --chown=1001:0 build/libs/redacted.war /config/dropins/redacted.war
COPY --chown=1001:0 src/main/liberty/config /config/
.
.
.
RUN VERBOSE=true features.sh
RUN VERBOSE=true configure.sh
```

We build the image using Jenkins. Sometimes (every 2 builds or so), the resulting image has missing features.

```
A feature definition could not be found for..
Could not resolve module
```

Pulling the broken image locally and running 
```
featureUtility installServerFeatures --acceptLicense defaultServer --noCache
```
sometimes install features, but sometimes it says it is up-to-date. Therefore, we enabled the VERBOSE flag on the features.sh to see what happens.

What we found out is that for the broken images the featureUtility does not report 100% progress.
```
20:07:00  + featureUtility installServerFeatures --acceptLicense defaultServer --noCache
20:07:01  [0m
20:07:02  Initializing ...
20:07:02  <---------------------> 0.00%
20:07:02  Using 8 threads to download artifacts.
20:07:02  <---------------------> 0.00%
20:07:04  Resolving remote features. 
.
.
.
20:07:38  Successfully installed feature servlet-3.1.
20:07:38  <====================-> 94.71%
20:07:38  <====================-> 94.94%
20:07:38  All features were successfully installed.
20:07:38  <====================-> 94.94%
20:07:38  <====================-> 99.94%
20:07:38  
20:07:38  Start product validation...
20:07:40  Product validation completed successfully.
````
While for all working images we see the 100% progress. Is that normal behaviour?

We initially suspected the docker cache, and sometimes pruning images from the build server helped, but I suspect that is just a coincidence.

Could this be a bug in featureUtility? Could it not report possible connectivity issues? Could this be related to SCC?

Any ideas on what the issue might be or how to further troubleshoot this are welcomed.

**Comment by jwalcorn** [comment]
Are you doing a “RUN features.sh” in your Dockerfile?  That’s needed with kernel-slim images (not needed with full images)

**Comment by bogdanmuresan** [comment]
> Are you doing a “RUN features.sh” in your Dockerfile? That’s needed with kernel-slim images (not needed with full images)

Yes (it's also added in the initial post). The problem is, that sometimes, this step seems to fail (or does not complete),  without error.

**Comment by leochr** [comment]
@bogdanmuresan Are you still encountering this issue? Is the frequency still the same (every other build or 2 builds)? Thanks.

**Comment by palkokec** [comment]
> @bogdanmuresan Are you still encountering this issue? Is the frequency still the same (every other build or 2 builds)? Thanks.

Hi @leochr - I am working on the issue with @bogdanmuresan . Usually the frequency to fix is every other build, but sporadically there were cases when it needed 2 builds.
I am going to try newest full image to see if the issue disappears.
Thanks for help

**Comment by zancrazvan** [comment]
Hello,

I'm facing the same issue described by @bogdanmuresan using the image `openliberty/open-liberty:22.0.0.6-kernel-slim-java11-openj9-ubi`

**Comment by zancrazvan** [comment]
Hello,

Adding this line in the Dockerfile fixed the issue.
`ENV JVM_ARGS="${JVM_ARGS} -Dcom.ibm.ws.install.featureUtility.artifactThreads=1"`

Looks like there is a concurrency issue during the features download

**Comment by kabicin** [comment]
I am able to reproduce this error using `open-liberty:21.0.0.10-kernel-slim-java11-openj9` as a base image. The `Starting installation ...` step of featureUtility has its progress bar understated by a few hundredths of percentage points and isn't rounded to a whole number as would expect. The discrepancy dominoes its way to the final percentage of the progress bar and it doesn't complete, similar to OP. This is more of an issue for the Liberty product team.  @jjiwooLim, can you take a look?

**Comment by leochr** [comment]
Thank you all for helping to get to the bottom of this! The fix will be included in an upcoming version of Open Liberty (likely 22.0.0.10).
