### ISSUE TITLE
UBI image tags not pointing to latest releases

### ISSUE THREAD

**Issue by idwerv** [OpenLiberty/ci.docker#296]
The following [UBI image tags in docker hub](https://hub.docker.com/r/openliberty/open-liberty) don't seem to be pointing to the latest 22.0.0.1 release:
```
latest                 -> 21.0.0.8
full-java8-openj9-ubi  -> 21.0.0.12
full-java8-ibmjava-ubi -> 21.0.0.12
full-java11-openj9-ubi -> 21.0.0.12

kernel-slim-*          -> 21.0.0.12
```
The [Ubuntu-based variant](https://hub.docker.com/_/open-liberty) seems to be pointing correctly to the 22.0.0.1 version of the image.

**Comment by leochr** [comment]
@idwerv Thanks for reaching out. We are aware of this issue and are working to address it.

@crpotter same issue as the one already reported in internal build repo ([here](https://github.ibm.com/was-docker/build-liberty-images-ubi/issues/159))

**Comment by idwerv** [comment]
Looks like the issue has been fixed. Thanks!
