### ISSUE TITLE
Change beta image to use latest supported version of Java (Java SE 17)

### ISSUE THREAD

**Issue by mbroz2** [OpenLiberty/ci.docker#304]
Currently, the `beta` tagged image uses Java SE 8.  Instead, we should change that to use the latest supported version of Java (aka, 17).
Also, consider dropping `beta-java11` image.

**Comment by leochr** [comment]
@mbroz2 The Java 17 support was recently added via the `beta-java17` tag. 
The only concern with updating `beta` tag from using Java 8 to 17 is breaking any users relying on Java 8. Perhaps that's okay since it is beta (?)

**Comment by mbroz2** [comment]
correct, since this is a beta, there are no concerns regarding regressions.  

I think we should also consider removing the `beta-java11` and `beta-java17` tags, and only having the `beta tag` (using Java SE 17), but that can be a separate issue/conversation.
fyi @NottyCode

**Comment by mbroz2** [comment]
this has been completed.
