### ISSUE TITLE
ARM64 support

### ISSUE THREAD

**Issue by odidev** [OpenLiberty/ci.docker#33]
I am trying to build ```Open-Liberty``` for ```arm64v8``` architecture.
Right now I can notice that this package depends on ```ibmjava:8-sfj-alipne``` and that also doesn't have support for ```arm64v8```.

Is there anyway, I can proceed with building this package for ARM.
I am working to get ```Open-liberty``` support ```arm64v8``` as official package.

Please guide, I would be happy to receive any kind of guidance.

**Comment by arthurdm** [comment]
Hi @odidev - as you have correctly stated, the official Open Liberty images currently builds from the IBM Java Docker images.   So can you please open an issue with [that repository](https://github.com/ibmruntimes/ci.docker/issues) with your request for `arm64v8` support?

**Comment by arthurdm** [comment]
Closing this, since we would need our dependent official layers to support `arm64v8` first.

**Comment by sdehors-ibm** [comment]
There is now an official Java docker image for arm64v8 
https://hub.docker.com/layers/arm64v8/ibm-semeru-runtimes/open-11-jre/images/sha256-51b328d2ce7504ab03a4ad642e76746abfe29d5b31b2e15ae8dfea425772152c?context=explore

**Comment by lagivan** [comment]
@arthurdm could you please reopen this? Apparently, the dependent official layer `icr.io/appcafe/ibm-semeru-runtimes:open-11-jdk-ubi` already supports `arm64` architecture.

**Comment by leochr** [comment]
@lagivan The support for arm64 is tracked via issue https://github.com/OpenLiberty/ci.docker/issues/241. The base images from Java for linux/arm64 are available, but we are working to add arm64 support to our build platform.
