### ISSUE TITLE
no matching manifest for linux/arm64/v8 in the manifest list entries

### ISSUE THREAD

**Issue by ttelang** [OpenLiberty/ci.docker#332]
Running the following command is throwing error as follow: 

```
$ docker pull icr.io/appcafe/open-liberty:full-java11-openj9-ubi
full-java11-openj9-ubi: Pulling from appcafe/open-liberty
no matching manifest for linux/arm64/v8 in the manifest list entries
````

Please advise how can I resolve this.

**Comment by leochr** [comment]
@ttelang Liberty doesn't provide arm64 based images at this time. This request is already tracked by this issue: https://github.com/OpenLiberty/ci.docker/issues/241

Specify the `--platform` parameter to pull one of the available images. Platform options: `linux/amd64` , `linux/s390x` or `linux/ppc64le` 
For example, `docker pull icr.io/appcafe/open-liberty:full-java11-openj9-ubi --platform linux/amd64`
