### ISSUE TITLE
Remove generated server.env from InstantOn dockerfile

### ISSUE THREAD

**Issue by dettmoney** [OpenLiberty/ci.docker#353]
Doing InstantOn startup performance testing has exposed a small (5-10ms) issue that has become relatively larger now that our startup times are around 100ms. Using the instanton beta Dockerfile.ubi.openjdk17, a server is created with the command "server create --template=javaee8", resulting in the creation of a server.env being generated in the server directory containing keystore_passord=abc123. This causes the server script at startup time to have to spend the aforementioned 5-10ms processing that created file. There is a --no-password property that can be passed into the server create command, but that still results in an empty server.env being created, and does not give us the startup savings. The server script still spends time processing the empty file.
I propose changing the dockerfile to remove the generated server.env.

**Comment by leochr** [comment]
Completed. Closing.
