### ISSUE TITLE
OpenJ9-based images

### ISSUE THREAD

**Issue by mthmulders** [OpenLiberty/ci.docker#37]
Inside [release/javaee8/java8](https://github.com/OpenLiberty/ci.docker/tree/master/release/javaee8/java8), there's a folder named `openj9`. That suggests there might be an image based on OpenJ9. But it seems it isn't published on Docker Hub.

Are there any plans to publish those?

**Comment by arthurdm** [comment]
Closing this issue as we have multiple OpenJ9-based images on Docker Hub now.
