### ISSUE TITLE
23.0.0.3 is missing in dockerhub

### ISSUE THREAD

**Issue by youssefgh** [OpenLiberty/ci.docker#392]
Am not sure if this CI project is supposed to build/push every openliberty tag.
But even if its true, i think it's important to have a 23.0.0.3 build since it's the only version available that fully support Jakarta EE 10 and MP 6

**Comment by leochr** [comment]
The images are typically released a few days to a week after the release of the Liberty runtime (binary). I'll follow up with the build team

**Comment by leochr** [comment]
Closing as resolved
