### ISSUE TITLE
23.0.0.4 no matching manifest for linux/amd64 in the manifest list entries

### ISSUE THREAD

**Issue by TimMnz09** [OpenLiberty/ci.docker#399]
When trying to pull newest open-liberty image from docker hub, I'm getting the following error:

```
> docker pull open-liberty:23.0.0.4-kernel-slim-java17-openj9

< 23.0.0.4-kernel-slim-java17-openj9: Pulling from library/open-liberty
< no matching manifest for linux/amd64 in the manifest list entries
```

**Comment by leochr** [comment]
@TimMnz09 The Ubuntu-based images are built by Docker and sometimes it takes awhile for the images to be available. I just tried now and was able to pull the amd64 and arm64 based images for `open-liberty:23.0.0.4-kernel-slim-java17-openj9` . Please give it another try

**Comment by TimMnz09** [comment]
Good to know :)
It works now!
