### ISSUE TITLE
Update to OL docker images for MicroProfile 2.1

### ISSUE THREAD

**Issue by kwsutter** [OpenLiberty/ci.docker#44]
Talking with @arthurdm, we will need a slight update to the OL images due to the MicroProfile 2.1 update due in 4Q2018:  [Epic for MicroProfile 2.1](https://github.com/OpenLiberty/open-liberty/issues/5574)

The only updated component for MicroProfile 2.1 is OpenTracing 1.2.  That piece of work is being tracked via their [Epic](https://github.ibm.com/was-liberty/WS-CD-Open/issues/13712).

The WAD review for both MP 2.1 and OT 1.2 is scheduled for next Thursday, Nov 8.

Any questions, contact either myself or Arthur.  Thanks!

**Comment by arthurdm** [comment]
For Open Liberty this may just be a simple change to a few of the `readme` files that say `MicroProfile 2.0`.  The server.xml is coming from `wlp/templates/servers/microProfile2/server.xml` in the binary zip, so as long as that gets updated to 2.1 (which I assume it will), the image will be good.

**Comment by kwsutter** [comment]
@arthurdm Should this Issue be closed?  Maybe reference the PR that was used to deliver these images?  Thanks!

**Comment by arthurdm** [comment]
@NottyCode - can you confirm that `wlp/templates/servers/microProfile2/server.xml` will be updated with MP 2.1?

**Comment by arthurdm** [comment]
Confirmed that the above server.xml was updated.  Closing this one.
