### ISSUE TITLE
Outdated links to Infinispan articles

### ISSUE THREAD

**Issue by dougbreaux** [OpenLiberty/ci.docker#443]
https://github.com/OpenLiberty/ci.docker#session-caching

Both of these links produce 404s

> the [Infinispan Operator](https://infinispan.org/infinispan-operator/master/operator.html). The [Infinispan Operator Tutorial](https://github.com/infinispan/infinispan-simple-tutorials/tree/master/operator)

**Comment by leochr** [comment]
@idlewis Same issue exists with [WL doc](https://github.com/WASdev/ci.docker/blob/main/README.md#session-caching). Please update it when you get a chance. Thank you.
