### ISSUE TITLE
Better error messages from Liberty

### ISSUE THREAD

**Issue by Hemankita** [OpenLiberty/ci.docker#45]
We are running our applocation using the docker image `websphere-liberty:webProfile8`

While running here, the following messages are displayed when I am running the application as non-root. 

```
[ERROR   ] CWWKS4000E: A configuration exception has occurred. The requested TokenService instance of type Ltpa2 could not be found.

[ERROR   ] CWWKS3005E: A configuration exception has occurred. No UserRegistry implementation service is available.  Ensure that you have a user registry configured.

[ERROR   ] CWWKS5604E: A JsonWebToken Principal can't be injected because one is not available. Protect the requesting resource so authentication occurs before the resource is accessed.
```
 
They got resolved once we updated the folder permission here. But the above error messages are little not clear. It seems like a more keystore problem than the permissions related to it.

**Comment by yeekangc** [comment]
I think:

(1) We may want to update the instructions for the relevant Docker images to clearly call out what to consider and to do now that non-root support has been added (and is the default)

(2) Better (error) messages from the runtime are always helpful

@arthurdm @chunlongliang-ibm

**Comment by yeekangc** [comment]
Yes, we noticed that the instruction is up-to-date.  If they can be more guided and the change between versions can be appropriately highlighted to make it easier for users to identify what they need to know and actions they need to take and for when, that will be great.

If we should re-file this issue in the WebSphere Liberty repo, let us know.  Thank you.

**Comment by yeekangc** [comment]
Same considerations apply now that Open Liberty is non-root by default.  The changes between versions can be better highlighted.

**Comment by NottyCode** [comment]
So I just saw these. I'm assuming these errors are only coming up if Liberty is running as non-root? That seems like a functional issue in open-liberty and not an issue with the dockerfiles themselves. At which point this needs to be moved into the open-liberty repository and assigned to a security SME. 

Are these still happening and what is being done to make sure this is moved to a repository where it can be addressed rather than left behind?

**Comment by yeekangc** [comment]
Issue moved to [OpenLiberty/open-liberty #7463](https://github.com/OpenLiberty/open-liberty/issues/7463) via [**ZenHub**](https://www.zenhub.com/)

**Comment by yeekangc** [comment]
Moved the issue per latest comment for the errors to be looked at from a security standpoint.

Still makes sense to have better instructions for non-root vs root for the Docker images.
