### ISSUE TITLE
Would you please provide sample docker file for "full" (WARNING: This is not an optimal build configuration)

### ISSUE THREAD

**Issue by uniquejava** [OpenLiberty/ci.docker#450]
As features.sh is extremely slow, so my Dockerfile is based on the "full" version.  I noticed this comment in the README

```Dockerfile
FROM public.ecr.aws/docker/library/websphere-liberty:23.0.0.8-full-java17-openj9

# This script will add the requested XML snippets to enable Liberty features and grow image to be fit-for-purpose using featureUtility.
# Only available in 'kernel-slim'. The 'full' tag already includes all features for convenience.
RUN features.sh
```

It says `RUN features.sh is Only available in 'kernel-slim'.` As I am not using 'kernel-slim', so I comment the line `RUN features.sh`, However, without this line, I still get this warning:

>  => [11/11] RUN configure.sh                                                                                                         516.7s
> => => # WARNING: This is not an optimal build configuration. Although features in server.xml will continue to be installed corr            
> => => #  be added to the Dockerfile prior to configure.sh. See https://ibm.biz/wl-app-image-template for a sample application > i         
               
Is it desirable? Should I include or remove `RUN features.sh` from Dockerfile for the `full` version base image?

<img width="1469" alt="image" src="https://github.com/OpenLiberty/ci.docker/assets/1049271/a5702a25-2190-4115-8ca6-061482b8734f">

**Comment by uniquejava** [comment]
I really like the build process can be as fast as possible, because each time actually only the war file changed. Can I remove configure.sh together in development environment.

**Comment by leochr** [comment]
Closing. Please reopen if there is any further inquiries. Thank you
