### ISSUE TITLE
Java 21 Support

### ISSUE THREAD

**Issue by berkant-k** [OpenLiberty/ci.docker#493]
Liberty and UBI already have Java 21 support. 

When will we have  container images with Java 21 support?

https://catalog.redhat.com/software/containers/ubi9/openjdk-21/6501cdb5c34ae048c44f7814?architecture=amd64&image=6554e3349ae133b73d1b4379

**Comment by engabduallah** [comment]
Hello Team, 

we appreciate if you can check this issue. 

thank you all

**Comment by leochr** [comment]
Hi, Liberty images are based on Semeru Runtimes and the Semeru 21 container images are not yet available.

We don't have a definite timeline to share at this time. But unofficially we expect the Liberty images with Semeru 21 to be available by the end of 1Q of 2024. Thank you.

**Comment by lenzch** [comment]
Looks like the changes for the Semeru 21 containers have just been merged.
https://github.com/ibmruntimes/semeru-containers/pull/88

**Comment by leochr** [comment]
Yes, we have some PRs in flight to use the new Java 21 image. If all goes well, Liberty images with Java 21 should be available when 24.0.0.1 is released end of this month.

**Comment by leochr** [comment]
Closing as complete. Details of Liberty images with Java 21 are included in the doc: https://openliberty.io/docs/latest/container-images.html
