### ISSUE TITLE
Output errors by default

### ISSUE THREAD

**Issue by leochr** [OpenLiberty/ci.docker#512]
Output the errors by default to stderr in all the helper scripts (configure.sh, populate_scc.sh, etc). As of now, `VERBOSE=true` must be enabled to see additional info.

Similar to https://github.com/WASdev/ci.docker/pull/559

- [x] Delivered to OL
- [x] Delivered to WL

**Comment by kabicin** [comment]
I did a find/replace to mirror the changes made to features.sh.  https://github.com/WASdev/ci.docker/pull/593 and https://github.com/OpenLiberty/ci.docker/pull/519

**Comment by leochr** [comment]
Closing as completed
