### ISSUE TITLE
Add OpenSSL to Alpine flavours

### ISSUE THREAD

**Issue by arthurdm** [OpenLiberty/ci.docker#54]
OpenSSL will be removed from the IBM JRE Alpine base image via PR https://github.com/ibmruntimes/ci.docker/pull/28

This issue is to make sure we explicitly add the OpenSSL package in Open Liberty's Alpine image.

**Comment by arthurdm** [comment]
This issue should also make the same update to the Ubuntu binaries, so that in the future we're not broken by changes in IBM JRE.

**Comment by Rachelwrq** [comment]
`openssl` is added and the branch is merged via the linked pr. Hence, closing the issue.
