### ISSUE TITLE
Using environment variable `PASSWORD`

### ISSUE THREAD

**Issue by andrewdes** [OpenLiberty/ci.docker#61]
When generating the `keystore.xml` (https://github.com/OpenLiberty/ci.docker/blob/master/official/javaee8/java8/ibmjava/helpers/runtime/docker-server.sh) the environment variable `PASSWORD` is set. This should be something less generic (perhaps `KEYSTORE_PASSWORD` or something similar).

One example where this caused issues was in the Kubernetes-config guide (https://openliberty.io/guides/kubernetes-microprofile-config.html), the environment variable `PASSWORD` is set inside the `ping-container`, but ends up getting overridden by the keystore password. So, later in the guide when trying to inject the value of the `PASSWORD` environment variable into the `PingResource` class, it is the wrong value.

**Comment by gkwan-ibm** [comment]
@yeekangc

**Comment by yeekangc** [comment]
Yes, this looks to be an overly generic variable that can easily clash with what a user may want to do or use.  Should consider something more specific or under a particular namespace.

**Comment by arthurdm** [comment]
I agree.   @leochr / @arturdzm - do we even need to export anything?  seems we just use the value in the snippet we're writing out.

**Comment by arturdzm** [comment]
export is not the issue, within the Entrypoint script it is set as we never quit docker start shell script until server stops.
We need to change variable name.
Needs to happen on both OL and WL

**Comment by arthurdm** [comment]
are those available as env vars?  When I do `docker exec <container> echo $PASSWORD` I don't get any values back.

**Comment by arturdzm** [comment]
Because you are creating a completely new shell environment when you exec. Also these variables exist only in context of process that runs entrypoint script and jvm. Setting any variables in shell script only affects current shell. To make them global usually they are added into files like ~/.bashrc.
Each new shell  process will executed that file automatically

**Comment by arthurdm** [comment]
This has been fixed.
