### ISSUE TITLE
kernel-java11-openj9 image on dockerhub is outdated

### ISSUE THREAD

**Issue by rafalmas** [OpenLiberty/ci.docker#75]
It looks like the image with tag 'kernel-java11-openj9' was last build on 26th of March, (and it contains OL 19.0.0.2) while docker file for that image was updated on 30th of April (and it contains OL 19.0.0.4). 

Could you please push new image to dockerhub and check why it was not done by CI pipeline.

**Comment by arthurdm** [comment]
Our OpenJ9 images are now in our official repository, so they get built automatically by Docker Inc.  Closing this as the issue has been resolved.
