### ISSUE TITLE
Incorrect hostname in Ingress configuration example

### ISSUE THREAD

**Issue by gasgithub** [OpenLiberty/ci.docker#95]
In the page that specifies Ingress configuration - https://github.com/OpenLiberty/ci.docker/blob/master/docs/ingress-configurations.md in the examples section it is written:

> For https://dev.foo.bar/ enter app.foo.bar as the ingress.host and / as the ingress.path.

and it should be `enter dev.foo.bar` , so dev instead of app.

**Comment by navidsh** [comment]
Good catch @gasgithub! Thanks

**Comment by navidsh** [comment]
Fixed in https://github.com/OpenLiberty/ci.docker/pull/96. Closing.
